name: Convert Markdown to HTML

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc
        pip install pygments

    - name: Prepare styles
      run: |
        # Generate Pygments CSS (GitHub-like theme)
        pygmentize -S github-dark -f html -a .highlight > styles.css
        
        # Create header with combined styles
        echo '<meta name="viewport" content="width=device-width, initial-scale=1">' > header.html
        echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/5.2.0/github-markdown.min.css">' >> header.html
        echo '<style>' >> header.html
        echo '.markdown-body { box-sizing: border-box; min-width: 200px; max-width: 980px; margin: 0 auto; padding: 45px; }' >> header.html
        echo '@media (max-width: 767px) { .markdown-body { padding: 15px; } }' >> header.html
        echo '</style>' >> header.html
        cat styles.css >> header.html

    - name: Convert Markdown to HTML
      run: |
        find . -name '*.md' -exec sh -c '
          for file; do
            output_html="${file%.md}.html"
            pandoc --standalone \
                   -H header.html \
                   --highlight-style=pygments \
                   --metadata pagetitle="$(basename "$file" .md)" \
                   -o "$output_html" "$file"
          done
        ' sh {} +

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: '**/*.html'