name: Convert Markdown to HTML

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc
        pip install pygments

    - name: Prepare styles
      run: |
        # Generate Pygments CSS
        pygmentize -S github-dark -f html -a .highlight > styles.css
        
        # Create header with wider layout
        #echo '<meta name="viewport" content="width=device-width, initial-scale=1">' > header.html
        #echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/5.2.0/github-markdown.min.css">' >> header.html
        #echo '<style>' >> header.html
        #echo '.markdown-body {' >> header.html
        #echo '  box-sizing: border-box;' >> header.html
        #echo '  width: 90%;' >> header.html
        #echo '  margin: 0 auto;' >> header.html
        #echo '  padding: 20px;'  # Reduced from 45px >> header.html
        #echo '}' >> header.html
        #echo '@media (max-width: 767px) { .markdown-body { padding: 15px; } }' >> header.html
        #echo '</style>' >> header.html
        cat styles.css >> header.html

    - name: Convert Markdown to HTML
      run: |
        find . -name '*.md' -exec sh -c '
          for file; do
            output_html="${file%.md}.html"
            pandoc --standalone \
                    #-H header.html \
                    --highlight-style=pygments \
                    --metadata pagetitle="$(basename "$file" .md)" \
                    -o "$output_html" "$file"
          done
        ' sh {} +

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: '**/*.html'