name: Convert and Package Docs
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc zip

    - name: Create output directory
      run: mkdir -p docs/assets

    - name: Copy assets
      run: cp -R css images docs/assets/ || true  # Ignore if no assets

    #- uses: xu-cheng/texlive-action@v2
    #  with:
    #    scheme: full
    #    run: |

    - name: Convert to HTML
      run: |
        find . -name '*.md' -exec sh -c '
          for file; do
            output_html="${file%.md}.html"
            pandoc "$file" -o "docs/$output_html" \
              --embed-resources --standalone
              #--css=assets/css/github.css
          done
        ' sh {} +

    #- name: Convert to PDF
    #  run: |
    #    find . -name '*.md' -exec sh -c '
    #      for file; do
    #          pandoc readme.md -o docs/readme.pdf \
    #          --pdf-engine=xelatex \
    #          --highlight-style=tango
    #      done
    #    ' sh {} +

    - name: Create ZIP archive
      run: |
        cd docs && zip -r ../technical-notes.zip ./*

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: technical-notes
        path: technical-notes.zip


    # Optional cloud storage upload examples:
    #- name: AWS S3 Upload
    #  if: ${{ false }}  # Set to true and configure credentials to enable
    #  uses: aws-actions/configure-aws-credentials@v2
    #  with:
    #    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
    #    aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
    #    aws-region: us-east-1

    #- name: Upload to S3
    #  if: ${{ false }}
    #  run: aws s3 cp technical-notes.zip s3://your-bucket/path/

    #- name: Deploy to GitHub Pages
    #  uses: peaceiris/actions-gh-pages@v3
    #  with:
    #    github_token: ${{ secrets.GITHUB_TOKEN }}
    #    publish_dir: ./docs