name: Convert and Package Docs
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-full zip

    - name: Create output directory
      run: mkdir -p docs/assets

    - name: Copy assets
      run: cp -R css images docs/assets/ || true  # Ignore if no assets

    - name: Convert to HTML
      run: |
        pandoc readme.md -o docs/readme.html \
        --standalone --self-contained \
        --css=assets/css/github.css \
        --metadata title="Technical Notes"

    - name: Convert to PDF
      run: |
        pandoc readme.md -o docs/readme.pdf \
        --pdf-engine=xelatex \
        --highlight-style=tango

    - name: Create ZIP archive
      run: |
        cd docs && zip -r ../technical-notes.zip ./*

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: technical-notes
        path: technical-notes.zip
